name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cargo build --verbose --no-default-features
        cargo build --verbose --all-features
        cargo build --examples
      env:
        OUT_DIR: target

    - name: Run tests
      run: |
        cargo test --verbose --no-default-features
        cargo test --verbose --all-features

    - name: Run cargo clippy
      run: |
        cargo clippy --no-default-features -- -D warnings
        cargo clippy --all-features -- -D warnings

    - name: Run cargo fmt
      run: |
        cargo fmt --all -- --check

    - name: Check shell completions
      if: matrix.os != 'windows-latest'
      run: |
        ls -A target/completions

    - name: Check shell scripts
      if: matrix.os == 'ubuntu-latest'
      run: >
        for file in scripts/*.sh; do
            [ -e "$file" ] || continue;
            bash -n "$file";
        done

    - name: Run lolcrab
      if: matrix.os != 'windows-latest'
      run: |
        echo "Version"
        ./target/debug/lolcrab --version
        echo "Help"
        ./target/debug/lolcrab --help
        echo "Test"
        ./target/debug/lolcrab <<< "Make your life more colorful"

    - name: Run lolcrab (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "Version"
        target/debug/lolcrab --version
        echo "Help"
        target/debug/lolcrab --help
        echo "Test"
        echo "Make your life more colorful" | target/debug/lolcrab
